os: linux
dist: xenial
language: ruby
cache: bundler
rvm:
  - "1.9.3"
services:
  - mongodb
  - mysql
bundler_args: --without development debug
before_script:
  - export TZ=America/Sao_Paulo
  - cp config/database.travis.yml config/database.yml
  - cp config/mongoid.travis.yml config/mongoid.yml
  - bundle exec rake db:create db:schema:load RAILS_ENV=test
env:
  - TEST_SUITE=abilities
script: "bundle exec rspec spec/$TEST_SUITE"
before_install:
  - gem install bundler -v 1.17.3
  - chmod +x ./script/grant_travis_privileges_on_mysql.sh
  - ./script/grant_travis_privileges_on_mysql.sh
